export const SET_FACTORY_ACTION = 'SET_FACTORY_ACTION';
export const ON_PLAYED_LOTTERY_ACTION = 'ON_PLAYED_LOTTERY_ACTION';
export const SET_CLOSED_LOTTERY_ACTION = 'SET_CLOSED_LOTTERY_ACTION';
export const UI_START_LOADING_ACTION = 'UI_START_LOADING_ACTION';
export const UI_STOP_LOADING_ACTION = 'UI_STOP_LOADING_ACTION';
export const OPEN_CLOSED_LOTTERY_DIALOG_ACTION = 'OPEN_CLOSED_LOTTERY_DIALOG_ACTION';
export const CLOSE_CLOSED_LOTTERY_DIALOG_ACTION = 'CLOSE_CLOSED_LOTTERY_DIALOG_ACTION';
export const SET_ACTIVE_LOTTERY_ACTION = 'SET_ACTIVE_LOTTERY_ACTION';