export const LOAD_FACTORY_ACTION = 'LOAD_FACTORY_ACTION';
export const SET_FACTORY_ACTION = 'SET_FACTORY_ACTION';
export const ON_PLAYED_LOTTERY_ACTION = 'ON_PLAYED_LOTTERY_ACTION';


export const UI_START_LOADING_ACTION = 'UI_START_LOADING_ACTION';
export const UI_STOP_LOADING_ACTION = 'UI_STOP_LOADING_ACTION';
export const OPEN_CREATE_LOTTERY_DIALOG_ACTION = 'OPEN_CREATE_LOTTERY_DIALOG_ACTION';
export const CLOSE_CREATE_LOTTERY_DIALOG_ACTION = 'CLOSE_CREATE_LOTTERY_DIALOG_ACTION';
export const CREATE_LOTTERY_ACTION = 'CREATE_LOTTERY_ACTION';
export const SET_NEW_LOTTERY_ADDRESS_ADDRESS = 'SET_NEW_LOTTERY_ADDRESS_ADDRESS';
export const SET_LOTTERY_ACTION = 'SET_LOTTERY_ACTION';
export const OPEN_PLAY_LOTTERY_DIALOG_ACTION = 'OPEN_PLAY_LOTTERY_DIALOG_ACTION';
export const CLOSE_PLAY_LOTTERY_DIALOG_ACTION = 'CLOSE_PLAY_LOTTERY_DIALOG_ACTION';
export const SET_ACTIVE_LOTTERY_ACTION = 'SET_ACTIVE_LOTTERY_ACTION';